[package]
name = "libmimalloc-sys2"
version = "0.1.45"
authors = ["Octavian Oncescu <octavonce@gmail.com>", "Long Yinan <lynweklm@gmail.com>"]
edition = "2018"
repository = "https://github.com/napi-rs/mimalloc-safe/tree/master/libmimalloc-sys"
keywords = ["allocator", "encrypted-heap", "performance"]
categories = ["memory-management", "api-bindings"]
description = "Sys crate wrapping the mimalloc allocator"
license = "MIT"
links = "mimalloc"
exclude = [
    "/c_src/mimalloc/bin",
    "/c_src/mimalloc/doc",
    "/c_src/mimalloc/docs",
    "/c_src/mimalloc/ide",
    "/c_src/mimalloc/test",
]

[dependencies]
cty = { version = "0.2", optional = true }
libc = "0.2"

[build-dependencies]
cmake = "0.1"

[features]
# For debug purposes
etw = []

secure = []
override = []
extended = ["cty"]
arena = []
local_dynamic_tls = []
no_thp = []
skip_collect_on_exit = []

# Show `extended` on docs.rs since it's the full API surface.
[package.metadata.docs.rs]
features = ["extended"]
